import type { Metadata } from "next";
import { Header } from "@/ui/Header";
import { Footer } from "@/ui/Footer";
import { merriweather } from "@/utils/fonts";
import "@/style/globals.css";
import { FloatingButton } from "@/ui/Components/FloatingButton";

export const metadata: Metadata = {
  title: "Clinica Fernández",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/Logo/icon.ico" type="image/x-icon" />
      </head>
      <body
        className={`${merriweather.className} bg-white-primary antialiased pt-3 grid min-h-[100dvh] overflow-x-hidden grid-rows-[auto_1fr_auto]`}
      >
        {/* Header */}
        <div className="max-w-[100dvw]">
          <Header />
        </div>

        {/* Main content */}
        <main className="py-16 max-w-[100dvw]">
          <FloatingButton />
          {children}
        </main>

        {/* Footer */}
        <div className="max-w-[100dvw]">
          <Footer />
        </div>
      </body>
    </html>
  );
}
